name: todo_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  intl: ^0.20.2
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  provider: ^6.1.5+1
  firebase_messaging: ^16.0.2
  firebase_analytics: ^12.0.2
  google_sign_in: ^7.2.0
  firebase_crashlytics: ^5.0.2
  firebase_storage: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
